name: Bake Cookie

on:   # Run after completion of documentation workflows to avoid merge conflicts
  workflow_run:
    workflows: ["Documentation Workflow"]
    types:
      - completed

jobs:

  bake:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Clean up
      run: |
        rm -r {{cookiecutter.project}}
    - name: Set up
      run: |
        mkdir {{cookiecutter.project}}
    - name: Bake
      run: |
        cp -R docs {{cookiecutter.project}}/docs
        cp -R .github {{cookiecutter.project}}/.github
        cp -R requirements.txt {{cookiecutter.project}}/requirements.txt
    - name: Top it off
      run: |
        cp -R project {{cookiecutter.project}}/{{cookiecutter.codename}}
        cp -R README.md {{cookiecutter.project}}/GUIDE.md
    - name: Spice it up
      run: |
        cp .gitignore {{cookiecutter.project}}/.gitignore
        cp LICENSE {{cookiecutter.project}}/LICENSE
    - name: Serve
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A && git commit --allow-empty -m "Baked Cookie"
        git push -u